mysql:
  host: 127.0.0.1:3306
  name: wblog
  user: root
  pass: 123456
pgsql:
  pass: 123456
zap:
  level: 'info'
  format: 'console'
  prefix: '[wblog]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true
qiniu_accesskey:
qiniu_secretkey:
qiniu_fileserver:
qiniu_bucket:
github_clientid:
github_clientsecret:
github_authurl: https://github.com/login/oauth/authorize?client_id=%s&scope=user:email&state=%s
# 与github配置的回调地址一致
github_redirecturl: http://localhost:6090/oauth2callback
github_token_url: https://github.com/login/oauth/access_token
github_scope:
smtp_username:
smtp_password:
smtp_host:
session_secret: wblog
reg: true
domain: www.baidu.com
public: static
addr: :6090
backup_key:
dsn: wblog.db?_loc=Asia/Shanghai
#dsn: root:mysql@/wblog?charset=utf8&parseTime=True&loc=Asia/Shanghai
notify_emails:
page_size: 5
smms_fileserver: https://sm.ms/api/upload